---
deployment:
      tasks:
        - export DEPLOYPATH=/home/tzwmaoom/repositories/StressAway
        - /bin/cp -r * $DEPLOYPATH                        #copy all recursively to $DEPLOYPATH
        
